############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Hobbies"
url = "/hobbies"
weight = 4

[[main]]
parent = "Hobbies"
name = "Baduanjin"
url = "/hobbies/baduanjin"
weight = 1

[[main]]
parent = "Hobbies"
name = "Films"
url = "/hobbies/films"
weight = 2

[[main]]
parent = "Hobbies"
name = "Journaling"
url = "/hobbies/journaling"
weight = 3

[[main]]
parent = "Hobbies"
name = "Photography"
url = "/hobbies/photography"
weight = 4

[[main]]
parent = "Hobbies"
name = "Reading"
url = "/hobbies/reading"
weight = 5

[[main]]
parent = "Hobbies"
name = "Travel"
url = "/hobbies/travel"
weight = 6

[[main]]
parent = "Hobbies"
name = "Writing"
url = "/hobbies/writing"
weight = 7

# [[main]]
# name = "Pages"
# weight = 4

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

# [[footer]]
# name = "Email"
# url = "mailto:lilinup90@gmail.com"
# weight = 3

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
